apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: conprof
  namespace: conprof
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conprof
  serviceName: conprof-governing-service
  template:
    metadata:
      labels:
        app: conprof
    spec:
      containers:
      - name: conprof
        image: quay.io/conprof/conprof:v0.1.0-dev
        imagePullPolicy: Always
        args:
        - all
        - --storage.tsdb.path=/conprof
        - --config.file=/etc/conprof/conprof.yaml
        volumeMounts:
        - mountPath: /etc/conprof
          name: config
          readOnly: true
        - mountPath: /conprof
          name: storage
      volumes:
      - name: config
        configMap:
          name: conprof
      - name: storage
        emptyDir: {}
