apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: conprof-main
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
