apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: conprof
    app.kubernetes.io/name: conprof
    app.kubernetes.io/version: master-2020-04-24-66b9527
  name: conprof
  namespace: conprof
